/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_greenstar_kernel_hardware_HWRS232 */

#ifndef _Included_com_greenstar_kernel_hardware_HWRS232
#define _Included_com_greenstar_kernel_hardware_HWRS232
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_greenstar_kernel_hardware_HWRS232
 * Method:    OpenSerialPort
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_greenstar_kernel_hardware_HWRS232_OpenSerialPort
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jdouble);

/*
 * Class:     com_greenstar_kernel_hardware_HWRS232
 * Method:    CloseSerialPort
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_greenstar_kernel_hardware_HWRS232_CloseSerialPort
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_greenstar_kernel_hardware_HWRS232
 * Method:    SendByteStream
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_greenstar_kernel_hardware_HWRS232_SendByteStream
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_greenstar_kernel_hardware_HWRS232
 * Method:    GetByteStream
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_greenstar_kernel_hardware_HWRS232_GetByteStream
  (JNIEnv *, jclass);

/*
 * Class:     com_greenstar_kernel_hardware_HWRS232
 * Method:    ResettSerialPort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_greenstar_kernel_hardware_HWRS232_ResettSerialPort
  (JNIEnv *, jclass);

/*
 * Class:     com_greenstar_kernel_hardware_HWRS232
 * Method:    GetAvailableSerialPorts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_greenstar_kernel_hardware_HWRS232_GetAvailableSerialPorts
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
